- name: GitHub-Profile-3D-Contrib
  # You may pin to the exact commit or the version.
  # uses: yoshi389111/github-profile-3d-contrib@7d95e7d4cdc028dd1e1cbd957d65f35efb12ae39
  uses: yoshi389111/github-profile-3d-contrib@v0.9.3
